name: Build Sapper and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build Sapper
        uses: truewebartisans/actions-sapper@master
        with:
          build_mode: "export"
          args: "--legacy --ext '.svelte .svx .md'"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: __sapper__/export
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
